version: '3.8'
services:
  dev-db:
    container_name: taskclimb-db
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: qwertyuiop
      POSTGRES_DB: userdb
    networks:
      - usernetwork
networks:
  usernetwork:
