version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5443:5432
    environment:
      POSTGRES_USER: greedyghoster
      POSTGRES_PASSWORD: qwertytrewq
      POSTGRES_DB: bestdb
    networks:
      - bestnetword
networks:
  bestnetword:
